<ul>
    <li>
        Version 2.2.1  januar 2013<br />
        Add cleanup to framework script<br />
        Fixed edit item with custom params <br />
        Remove $fielddef.file_location. Added $item->file_location to orig_summary_template.tpl and orig_detail_template.tpl <br />
        Bugfixes
        <br />        
    </li> 
    <li>
        Version 2.3.1  januar 2013<br />
        Add cleanup to upgrade script<br />
        Fixed edit item preview<br />        
    </li> 
    <li>
        Version 2.3  januar 2013<br />
        Add custom fields to gallery.<br />
        Add new field type dropdown from UDT.<br />
        Add new option to settings - filter.<br />
        Add custom fields for admin filter to option tab.<br />
        Rewrite some part of module with inheritance modules.<br />
        Rename uploads dirs with _ prefix (hide for dropzone)<br />
        Remove frontend option from fields tab. <br />
        Some bugfixes.
    </li> 
    <li>
        Version 2.2.4  october 2012 <br />
        Some bug fixes related to new smarty caching system.
    </li> 
    <li>
        Version 2.2.2  august 2012 <br />
        Options tab moved outside default admin landing page
        Some minor fixes
    </li> 
</ul>
